#!/usr/bin/env bash
# dont love me
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid | kill $$' SIGQUIT
echo $$ > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
