#!/usr/bin/env bash
# this script manages the manage_my_process daemon
PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"
case "$1" in
	start)
		$PROCESS &
		echo $! > "$PIDFILE"
		echo "manage_my_process started"
		;;
	stop)
		if [ -f "$PIDFILE" ]; then
			kill "$(cat "$PIDFILE")" 2>/dev/null
			rm -f "$PIDFILE"
		fi
		echo "manage_my_process stopped"
		;;
	restart)
                if [ -f "$PIDFILE" ]; then
                        kill "$(cat "$PIDFILE")" 2>/dev/null
                        rm -f "$PIDFILE"
                fi
                echo "manage_my_process stopped"

                $PROCESS &
                echo $! > "$PIDFILE"
                echo "manage_my_process restarted"
                ;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
